apiVersion: v1
kind: Secret
metadata:
  name: p-secret-fb
type: Opaque
data:
  DB_HOST: ZGJwZXNidWsuY3oxbmNvcHRsZGJxLmFwLXNvdXRoZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t 
  DB_USER: cm9vdA==
  DB_PASS: dGVzdDEyMzQ1
  DB_NAME: ZGJzb3NtZWRfcHJvZA== 
